server:
  port: 10001

spring:
   application:
    name: dept-consumer
      
eureka:
  client:
    service-url:
      defaultZone: http://eureka001.com:7001/eureka,http://eureka002.com:7002/eureka/
      


