server:
  port: 10003

eureka:
  client:
    service-url:
      defaultZone: http://eureka001.com:7001/eureka,http://eureka002.com:7002/eureka/
    register-with-eureka: false #不把自己注册进去服务

feign:
  hystrix:
    enabled: true